highcharts:
  jshead:
    - js/jquery-1.9.1.min.js
    - js/highcharts.js
    - js/highcharts-more.js
    - js/exporting.js
  cdn:
    jshead:
      - "//code.jquery.com/jquery-1.9.1.min.js"
      - "//code.highcharts.com/highcharts.js"
      - //code.highcharts.com/highcharts-more.js"
      - "//code.highcharts.com/modules/exporting.js"
